# Site settings
title: Francesca Capel
description: Francesca Capel - Astrophysicist
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "http://francescacapel.com" 

# User settings
username: Francesca Capel
user_description: Astrophysicist
user_title: Astrophysicist
email: f.capel@tum.de
#twitter_username: 
github_username: cescalara
#gplus_username:

# Google-analytics
google-analytics:
  id: UA-154766493-1

exclude: ['package.json', 'src' , 'node_modules']
