# Site settings
title: Francesca Capel
description: Francesca Capel - Astrophysics PhD Student
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "http://francescacapel.com" 

# User settings
username: Francesca Capel
user_description: Astrophysics PhD Student
user_title: Astrophysics PhD Student
email: capel@kth.se
#twitter_username: 
github_username:  cescalara
#gplus_username:

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
